export const THEMES = [
    ['atlas', 'Atlas', 'Measured, botanical, calm'], ['halo', 'Halo', 'Airy, luminous, precise'],
    ['voyage', 'Voyage', 'Marine, expansive, fluid'], ['forge', 'Forge', 'Industrial, compact, exact'],
    ['meridian', 'Meridian', 'Editorial, warm, confident'], ['atelier', 'Atelier', 'Soft, tactile, considered']
];
export const LANGUAGES = [['python', 'Python'], ['javascript', 'JavaScript · server'], ['java', 'Java'], ['cpp', 'C++'], ['c', 'C'], ['sql', 'SQL · SQLite']];
export const RUNTIMES = [...LANGUAGES, ['html', 'HTML'], ['css', 'CSS'], ['browser-js', 'JavaScript · browser']];
export const DIFFICULTIES = ['Easy', 'Medium', 'Hard', 'Extreme'];
export const XP = { Easy: 30, Medium: 60, Hard: 100, Extreme: 150 };
export const KINDS = { challenge: 'Challenges', daily: 'Daily Challenges', debug: 'Debug Detective', track: 'Track problems' };
export const MESSAGE_KINDS = ['Work saved', 'Saved locally', 'Conflict', 'At risk', 'Completed', 'Refused', 'Failed but retryable', 'Execution started', 'Execution stopped', 'Execution succeeded', 'Execution failed', 'Accepted', 'Not accepted', 'Hint revealed', 'Editorial unlocked', 'Answer', 'No match', 'Skills next action', 'Daily completed', 'Track completed', 'Subject completed', 'Course completed', 'Solutions milestone', 'Test submitted', 'Test auto-submitted', 'Grading', 'Result ready', 'Test invalidated', 'Changed after use', 'Progress reset', 'Achievement unlocked', 'Level crossed', 'Streak milestone', 'Certificate issued', 'Certificate revoked', 'Dependency unavailable', 'Maintenance active', 'Tour step', 'Tour completed'];
export const EXPRESSIONS = ['Neutral', 'Attentive', 'Thinking', 'Informational', 'Encouraging', 'Warning', 'Serious', 'Success', 'Celebration'];
export const TONES = ['Neutral', 'Informational', 'Encouraging', 'Warning', 'Serious'];
export const now = () => new Date().toISOString();
export const id = (prefix = 'id') => `${prefix}-${globalThis.crypto.randomUUID().slice(0, 8)}`;
export function dateAfter(days = 0) { const d = new Date(); d.setUTCDate(d.getUTCDate() + days); return d.toISOString().slice(0, 10); }
export const starter = {
    python: 'import sys\n\ndef solve():\n    # Read the input and implement your solution.\n    n = int(sys.stdin.readline())\n    pass\n\nif __name__ == "__main__":\n    solve()\n',
    javascript: "const fs = require('fs');\nconst input = fs.readFileSync(0, 'utf8').trim();\n\nfunction solve(input) {\n  // Implement your solution.\n}\n\nsolve(input);\n",
    java: 'import java.util.*;\n\npublic class Main {\n    public static void main(String[] args) {\n        Scanner input = new Scanner(System.in);\n        // Implement your solution.\n    }\n}\n',
    cpp: '#include <iostream>\nusing namespace std;\n\nint main() {\n    // Implement your solution.\n    return 0;\n}\n',
    c: '#include <stdio.h>\n\nint main(void) {\n    /* Implement your solution. */\n    return 0;\n}\n', sql: '-- Query the supplied SQLite dataset.\nSELECT * FROM learners;\n'
};
const pyReference = 'import sys\n\ndef parentheses(n):\n    result = []\n    def visit(prefix, opened, closed):\n        if len(prefix) == 2 * n:\n            result.append(prefix)\n            return\n        if opened < n:\n            visit(prefix + "(", opened + 1, closed)\n        if closed < opened:\n            visit(prefix + ")", opened, closed + 1)\n    visit("", 0, 0)\n    return result\n\nif __name__ == "__main__":\n    n = int(sys.stdin.readline())\n    print("\\n".join(parentheses(n)))\n';
const jsReference = "const fs = require('fs');\nconst n = Number(fs.readFileSync(0, 'utf8').trim());\nconst result = [];\nfunction visit(prefix, opened, closed) {\n  if (prefix.length === 2 * n) {\n    result.push(prefix);\n    return;\n  }\n  if (opened < n) visit(prefix + '(', opened + 1, closed);\n  if (closed < opened) visit(prefix + ')', opened, closed + 1);\n}\nvisit('', 0, 0);\nconsole.log(result.join('\\n'));\n";
export function newProblem(kind = 'challenge', track = null) {
    const language = track?.language || 'python';
    return { id: id(kind), kind, trackId: track?.id || '', title: '', slug: '', description: '', difficulty: 'Easy', primarySkill: 'Algorithms', topic: 'Arrays', tags: '', inputDescription: '', outputDescription: '', constraints: '', interface: 'console', comparison: 'Exact (normalize line endings and one final newline)', timeMs: 5000, memoryMiB: 128, languages: [{ language, starter: starter[language] || '', reference: '', editorial: '' }], cases: [], hints: [], sqlSchema: 'CREATE TABLE learners (id INTEGER PRIMARY KEY, name TEXT, score INTEGER);', sqlDataset: "INSERT INTO learners VALUES (1, 'Asha', 90), (2, 'Ravi', 70);", rowOrder: true, tolerance: 0, date: kind === 'daily' ? dateAfter(1) : '', bonus: 40, mode: 'Practice only', duration: 30, windows: 3, bugCount: 1, bugTypes: 'logic', internalNote: '', source: 'Original authored content', sourceDate: '', permission: '', prerequisite: '', status: 'Draft', revision: 1, updated: now() };
}
export function newTrack() { return { id: id('track'), title: '', description: '', language: 'python', order: [], prerequisite: '', status: 'Draft', revision: 1, updated: now() }; }
export function newQuestion(type = 'single') { return { id: id('q'), type, title: '', options: ['', '', '', ''], correct: [0], number: 0, tolerance: 0, relative: false, boolean: true, marks: 4, penalty: 0, difficulty: 'Easy', skill: 'Algorithms', topic: 'Arrays', explanation: '', targetTime: 60, code: type === 'coding' ? newProblem('challenge') : null }; }
export function newPaper(type = 'Mock', companyId = '') { return { id: id('paper'), title: '', description: '', type, companyId, role: '', year: new Date().getFullYear(), provenance: 'Pattern', source: '', sourceDate: '', permission: '', category: 'Aptitude', difficulty: 'Medium', duration: 60, grace: 60, passPercent: 50, opens: '', closes: '', proctoring: 'Standard', eventLimit: 3, fullscreen: false, clipboard: false, restrictedNavigation: false, featured: false, timer: true, palette: true, review: true, skip: true, revisit: true, sectionSwitch: true, shuffleQuestions: false, shuffleOptions: false, revealAnswers: true, revealExplanations: true, notify: false, freshTest: false, sections: [{ id: id('section'), title: 'Section 1', subject: 'Aptitude', briefing: '', duration: 0, runAllowance: '', included: true, questions: [] }], status: 'Draft', revision: 1, updated: now() }; }
export function newLesson(type = 'reading') { return { id: id('lesson'), title: '', type, outcomes: '', required: true, body: '', blocks: [], questions: [], timer: 0, passPercent: 0, shuffleQuestions: false, shuffleOptions: false, videoName: '', videoState: 'No video', captions: '', transcript: '', templateId: '', activity: '', status: 'Draft' }; }
export function newSubject(format = 'Lessons') { return { id: id('subject'), title: '', description: '', format, difficulty: 'Easy', tags: '', skill: 'Networks', outcomes: '', audience: '', priorKnowledge: 'None', estimatedMinutes: 60, tools: '', navigation: 'Open', prerequisite: '', next: '', certificate: format === 'Video Courses', presentation: 'Platform style', chapters: [{ id: id('chapter'), title: 'Chapter 1', lessons: [] }], source: 'Original authored content', status: 'Draft', revision: 1, updated: now() }; }
export function newTemplate(runtime = 'python') {
    const files = { python: ['main.py', 'print("Hello, builder. Your project starts here!")\n'], javascript: ['main.js', 'console.log("Hello, builder. Your project starts here!");\n'], java: ['Main.java', 'public class Main {\n    public static void main(String[] args) {\n        System.out.println("Hello, builder!");\n    }\n}\n'], cpp: ['main.cpp', '#include <iostream>\nint main() { std::cout << "Hello, builder!\\n"; }\n'], c: ['main.c', '#include <stdio.h>\nint main(void) { printf("Hello, builder!\\n"); return 0; }\n'], html: ['index.html', '<!doctype html>\n<html lang="en">\n<head><title>My project</title></head>\n<body><h1>Hello, builder.</h1></body>\n</html>'] };
    const [path, content] = files[runtime] || files.html;
    return { id: id('template'), title: '', description: '', runtime, entry: path, files: [{ path, content }], folders: [], tasks: [], tags: '', status: 'Draft', revision: 1, updated: now() };
}
function base(r, status = 'Draft') { return { ...r, status, updated: now(), revision: 1 }; }
export function createSeed() {
    const generate = { ...newProblem(), id: 'challenge-parentheses', title: 'Generate Parentheses', slug: 'generate-parentheses', description: 'Given **n pairs of parentheses**, generate every combination of well-formed parentheses.\n\nReturn one combination per line in lexicographic order.', difficulty: 'Medium', topic: 'Recursion & Backtracking', tags: 'recursion, backtracking, strings', inputDescription: 'One integer n: the number of pairs.', outputDescription: 'Each line contains one valid arrangement of n pairs.', constraints: '1 ≤ n ≤ 8', languages: [{ language: 'python', starter: starter.python, reference: pyReference, editorial: 'Use backtracking. Add an opening parenthesis while opened < n, and a closing parenthesis only while closed < opened.\n\nTime: proportional to the output size.' }, { language: 'javascript', starter: starter.javascript, reference: jsReference, editorial: 'Track opened and closed counts. The recursion only extends a valid prefix.' }], cases: [{ id: 'case-1', visibility: 'Visible', input: '3', expected: '((()))\n(()())\n(())()\n()(())\n()()()', explanation: 'The five well-formed arrangements for three pairs.' }, { id: 'case-2', visibility: 'Visible', input: '1', expected: '()', explanation: 'Exactly one pair.' }, { id: 'case-3', visibility: 'Hidden', input: '2', expected: '(())\n()()', explanation: '' }], hints: [{ id: 'hint-1', title: 'Build a valid prefix', body: 'Only add a closing parenthesis when an unmatched opening parenthesis exists.' }, { id: 'hint-2', title: 'Track two counts', body: 'Use opened and closed counts. Stop when the string contains 2 × n characters.' }], status: 'Published', sampleStats: { attempted: 120, solved: 83 } };
    const debug = { ...newProblem('debug'), id: 'debug-off-by-one', title: 'The Missing Last Number', slug: 'missing-last-number', description: 'This program should print the sum of the integers from 1 through n, inclusive. Find and fix the incorrect boundary.', difficulty: 'Easy', inputDescription: 'An integer n.', outputDescription: 'One integer: the inclusive sum.', constraints: '1 ≤ n ≤ 10,000', mode: 'Timed then practice', bugTypes: 'off-by-one', languages: [{ language: 'python', starter: 'n = int(input())\ntotal = 0\nfor value in range(1, n):\n    total += value\nprint(total)\n', reference: 'n = int(input())\ntotal = 0\nfor value in range(1, n + 1):\n    total += value\nprint(total)\n', editorial: 'range stops before its upper bound. Include n by using n + 1. The input n = 1 is the smallest case that exposes the bug.' }], cases: [{ id: 'dbg-1', visibility: 'Visible', input: '5', expected: '15', explanation: '1 + 2 + 3 + 4 + 5 = 15.' }, { id: 'dbg-2', visibility: 'Hidden', input: '1', expected: '1', explanation: '' }], status: 'Published', sampleStats: { attempted: 64, solved: 50 } };
    const daily = { ...structuredClone(generate), id: 'daily-parentheses', kind: 'daily', title: 'A Balanced Tomorrow', slug: 'balanced-tomorrow', date: dateAfter(1), bonus: 40, status: 'Draft', sampleStats: { attempted: 0, solved: 0 } };
    const track = base({ ...newTrack(), id: 'track-python', title: 'Python Foundations', description: 'Build confident fundamentals, one independent exercise at a time.', order: ['track-sum'] }, 'Published');
    const trackProblem = { ...structuredClone(debug), id: 'track-sum', kind: 'track', trackId: track.id, title: 'Sum from One to N', description: 'Read n and print the sum from 1 through n.', languages: [{ language: 'python', starter: starter.python, reference: 'n = int(input())\nprint(n * (n + 1) // 2)\n', editorial: 'The arithmetic-series formula avoids a loop.' }], mode: 'Practice only', sampleStats: { attempted: 75, solved: 68 } };
    const p = newPaper();
    p.id = 'paper-foundations';
    p.title = 'Developer Foundations';
    p.description = 'A balanced practice paper covering reasoning and coding.';
    const q1 = { ...newQuestion('single'), id: 'q-array', title: 'Which structure provides first-in, first-out behavior?', options: ['Stack', 'Queue', 'Tree', 'Set'], correct: [1], skill: 'Data Structures' };
    const q2 = { ...newQuestion('multiple'), id: 'q-numeric', title: 'Select all even prime numbers.', options: ['2', '3', '5', '8'], correct: [0] };
    const q3 = { ...newQuestion('numerical'), id: 'q-number', title: 'What is 15% of 200?', number: 30 };
    const q4 = { ...newQuestion('boolean'), id: 'q-bool', title: 'An empty string has length zero.', boolean: true };
    const q5 = { ...newQuestion('coding'), id: 'q-code', title: 'Generate Parentheses', code: structuredClone(generate) };
    p.sections = [{ id: 'section-reasoning', title: 'Reasoning', subject: 'Aptitude', briefing: 'Read each question carefully.', duration: 20, runAllowance: '', included: true, questions: [q1, q2, q3, q4] }, { id: 'section-coding', title: 'Coding', subject: 'Programming', briefing: 'Run visible samples before you submit.', duration: 40, runAllowance: 10, included: true, questions: [q5] }];
    const company = { id: 'company-northstar', title: 'Northstar Technology', description: 'Fictional company for local demonstration.', roles: ['Software Engineer', 'Graduate Developer'], customDefaults: false, marks: 4, penalty: 0, active: true, revision: 1, updated: now() };
    const cp = { ...structuredClone(p), id: 'paper-company', type: 'Company', companyId: company.id, role: company.roles[1], title: 'Graduate Developer · Pattern', description: 'A fictional, structured practice pattern. Not an actual employer paper.', passPercent: null, status: 'Draft' };
    const t = newTemplate('html');
    t.id = 'template-web';
    t.title = 'Personal Reading List';
    t.description = 'A small browser-native project with a useful, editable starting point.';
    t.files = [{ path: 'index.html', content: '<!doctype html>\n<html lang="en">\n<head>\n  <meta charset="utf-8">\n  <title>My reading list</title>\n  <link rel="stylesheet" href="style.css">\n</head>\n<body>\n  <main>\n    <h1>My reading list</h1>\n    <p>Your next good read starts here.</p>\n    <ul id="books"><li>The Pragmatic Programmer</li></ul>\n  </main>\n</body>\n</html>\n' }, { path: 'style.css', content: 'body { font: 16px system-ui; background: #f4f6f2; color: #25322a; }\nmain { max-width: 680px; margin: 80px auto; padding: 32px; background: white; border-radius: 16px; }\nh1 { letter-spacing: -0.04em; }\n' }, { path: 'app.js', content: '// Add interactivity to your reading list.\n' }];
    t.tasks = [{ id: 'task-1', title: 'Add three favorite books', instructions: 'Edit the list in index.html.', file: 'index.html' }, { id: 'task-2', title: 'Personalize the page', instructions: 'Update typography and spacing.', file: 'style.css' }];
    t.status = 'Published';
    const s = newSubject();
    s.id = 'subject-networks';
    s.title = 'Computer Networks';
    s.description = 'Understand how devices communicate, from your first packet to the web.';
    s.outcomes = 'Explain how packets travel\nDistinguish the internet and an intranet';
    s.audience = 'Curious beginners';
    s.tools = 'Browser, terminal';
    const reading = { ...newLesson(), id: 'lesson-internet', title: 'What is the internet?', outcomes: 'Describe a network of networks', body: '## A network of networks\nThe internet connects independently operated networks. Devices exchange small messages called packets.\n\n## A useful distinction\nAn intranet is a private network used within an organization.', blocks: [{ id: 'block-code', type: 'executable', language: 'python', content: 'print("Hello from your first packet!")\n' }] };
    const video = { ...newLesson('video'), id: 'lesson-packets', title: 'A packet’s journey', outcomes: 'Trace the journey of a packet', videoName: 'packets-demo.mp4', videoState: 'Ready', captions: '00:00:00.000 --> 00:00:04.000\nLet’s follow a packet.', transcript: 'A packet travels through several networks to reach its destination.' };
    const quiz = { ...newLesson('quiz'), id: 'lesson-quiz', title: 'Check your understanding', outcomes: 'Identify basic network terms', questions: [{ ...q1, id: 'cq-1', title: 'What is a private organizational network called?', options: ['Internet', 'Intranet', 'Packet', 'Router'], correct: [1], penalty: 0 }] };
    const project = { ...newLesson('project'), id: 'lesson-project', title: 'Build your reading list', outcomes: 'Apply a simple web template', templateId: t.id };
    const linked = { ...newLesson('activity'), id: 'lesson-practice', title: 'Practise your first algorithm', outcomes: 'Solve an independent practice problem', activity: '/challenges/challenge-parentheses' };
    s.chapters = [{ id: 'chapter-basics', title: 'The foundations', lessons: [reading, video, quiz, project, linked] }];
    const vs = { ...newSubject('Video Courses'), id: 'subject-video', title: 'Programming, Explained', description: 'Short, focused video lessons.', outcomes: 'Read a simple program', audience: 'New programmers', chapters: [{ id: 'chapter-intro', title: 'Get started', lessons: [{ ...structuredClone(video), id: 'lesson-video-intro', title: 'Meet your first program' }] }] };
    const facts = ['Your work is saved.', 'Your work is saved on this device.', 'A newer saved version is available.', 'Your work is not confirmed saved.', 'This activity is complete.', 'This action is not available.', 'This action did not finish. Please try again.', 'Your program is running.', 'Your program has stopped.', 'Your program finished successfully.', 'The program could not finish.', 'Your solution was accepted.', 'This solution was not accepted.', 'Your requested hint is available.', 'The explanation is now available.', 'Here is the approved product guidance.', 'No matching answer was found.', 'A next activity is available on Skills.', 'This Daily is complete.', 'This Track is complete.', 'This subject is complete.', 'This video subject is complete.', 'You reached a saved-solutions milestone.', 'Your test answers were submitted.', 'Your test ended and its saved answers were submitted.', 'Your answers are saved. Your result is being calculated.', 'Your result is ready.', 'This test was invalidated. Read its result for the next step.', 'This content has changed since your last visit.', 'Your progress was reset in the stated areas.', 'You unlocked an achievement.', 'You reached a new level.', 'You reached a Daily streak milestone.', 'Your certificate is ready.', 'This certificate is no longer valid.', 'This capability is temporarily unavailable.', 'Maintenance is in progress.', 'This is one of your Home landmarks.', 'Your orientation is complete.'];
    return {
        version: 1, savedAt: now(), problems: [generate, daily, debug, trackProblem], tracks: [track], papers: [p, cp], companies: [company], subjects: [s, vs], templates: [t],
        kb: [{ id: 'kb-hints', title: 'Do hints cost Credits?', answer: 'Authored hints are free. Credits apply only to the three explicitly requested generated-assistance actions.', synonyms: 'hint cost, free hints', tags: 'practice, credits', source: 'docs/domains/Practice/Practice.md', reviewed: dateAfter(-12), status: 'Published', revision: 1, updated: now() }],
        responseSets: [{ id: 'responses-main', title: 'WizBit response set', description: 'All 39 authored message kinds, maintained as one coordinated set.', status: 'Draft', revision: 1, updated: now(), items: MESSAGE_KINDS.map((title, i) => ({ id: `response-${i}`, title, fact: facts[i], flourish: '', tone: i === 3 ? 'Warning' : 'Informational', expression: i === 3 ? 'Warning' : 'Informational', acknowledgement: [2, 3, 5, 6, 34, 35, 36].includes(i), celebrate: [18, 19, 20, 21, 22, 30, 31, 32].includes(i) })) }],
        responses: MESSAGE_KINDS.map((title, i) => ({ id: `response-${i}`, title, fact: facts[i], flourish: '', tone: i === 3 ? 'Warning' : 'Informational', expression: i === 3 ? 'Warning' : 'Informational', acknowledgement: [2, 3, 5, 6, 34, 35, 36].includes(i), celebrate: [18, 19, 20, 21, 22, 30, 31, 32].includes(i), status: 'Draft', revision: 1, updated: now() })),
        people: [{ id: 'person-asha', title: 'Asha Rao', email: 'asha@example.test', role: 'User', standing: 'In good standing', membership: 'Active', xp: 1240, credits: 4200, joined: '2026-06-01', end: '2031-06-01' }, { id: 'person-ravi', title: 'Ravi Kumar', email: 'ravi@example.test', role: 'User', standing: 'Suspended', membership: 'Active', xp: 640, credits: 3600, joined: '2026-07-01', end: '2031-07-01' }, { id: 'person-meera', title: 'Meera Sen', email: 'meera@example.test', role: 'Admin', standing: 'In good standing', membership: 'Staff access', xp: 0, credits: 0, joined: '2026-06-01', end: '' }],
        requests: [{ id: 'request-1', title: 'More SQL joins practice', description: 'A step-by-step set of SQLite join exercises would help.', area: 'Challenges', status: 'Pending', note: '', target: '', created: dateAfter(-2) }, { id: 'request-2', title: 'A beginner web project template', description: 'A reading-list template with simple HTML and CSS.', area: 'Workspace', status: 'Approved', note: 'A suitable template is in review.', target: '', created: dateAfter(-4) }],
        reports: [{ id: 'report-1', title: 'Example wording could be clearer', target: '/admin/challenges/challenge-parentheses', reason: 'Incorrect', description: 'Please clarify whether output should be sorted.', status: 'Open', outcome: '', note: '', created: dateAfter(-1) }],
        certificates: [{ id: 'certificate-1', title: 'Computer Networks', person: 'Asha Rao', personId: 'person-asha', name: 'Asha Rao', status: 'Issued', issued: '2026-08-14', proposal: 'Asha R. Rao', proposalReason: 'Please use the name I use academically.', proposalState: 'Pending', history: ['Issued after eligible completion.'] }, { id: 'certificate-2', title: 'Programming, Explained', person: 'Ravi Kumar', personId: 'person-ravi', name: 'Ravi Kumar', status: 'Generation failed', issued: '', proposal: '', history: ['Generation failed. Original award preserved.'] }],
        jobs: [{ id: 'job-reward', title: 'First-solve reward delivery', kind: 'Reward', state: 'Failed', age: '12 min', reason: 'Temporary delivery failure', tries: 3, target: '/admin/economy/failed-rewards' }, { id: 'job-identity', title: 'Main-site membership change', kind: 'Identity', state: 'Failed', age: '5 min', reason: 'Verification response unavailable', tries: 2, target: '/admin/identity-delivery' }, { id: 'job-grading', title: 'Recorded test grading', kind: 'Grading', state: 'Pending', age: '42 sec', reason: 'Automatic recovery scheduled', tries: 1, target: '/admin/papers' }],
        broadcasts: [], holds: [], erasures: [], maintenance: [], audit: [],
        vocabulary: [{ id: 'skill-algorithms', title: 'Algorithms', type: 'Skill', parent: '', status: 'Active' }, { id: 'skill-networks', title: 'Networks', type: 'Skill', parent: '', status: 'Active' }, { id: 'topic-arrays', title: 'Arrays', type: 'Topic', parent: 'skill-algorithms', status: 'Active' }, { id: 'topic-recursion', title: 'Recursion & Backtracking', type: 'Topic', parent: 'skill-algorithms', status: 'Active' }],
        bugTypes: ['off-by-one', 'boundary', 'state', 'logic', 'resource', 'typo'],
        settings: { easyXP: 30, mediumXP: 60, hardXP: 100, extremeXP: 150, dailyBonus: 40, subjectXP: 250, mockCompleteXP: 200, mockPassXP: 300, baseCredits: 5000, continuationCredits: 5000, errorPrice: 100, passagePrice: 150, analysisPrice: 250, activeMinutes: 120, easyEvidence: 55, mediumEvidence: 70, hardEvidence: 85, extremeEvidence: 100, nudgeAllowance: 1, homeSuggestion: '/courses/subject-networks', homeLine: 'Understand the networks behind your everyday internet.', nextLearn: '/courses/subject-networks', nextPractice: '/challenges/challenge-parentheses', nextAssess: '/mock-tests', nextApply: '/projects', nudgeEnabled: true, nudgeDays: 7, matchThreshold: 0.65, matchMargin: 0.15, character: 'Orbital', characterAccent: '#9dddac', provenance: 'Original authored content' },
        testRecords: [{ id: 'test-demo', paperId: p.id, title: p.title, status: 'Final', proctoring: 'Standard', events: [{ time: '10:12:08', event: 'Window focus changed', counted: true }, { time: '10:14:03', event: 'Fullscreen exited', counted: false }], ending: 'Learner submitted', history: [] }]
    };
}
