import { esc, icon, button, link, badge, field, toggle, section, heading, table, empty, note, metric, tabs, download, csv, markdown } from '../ui.js';
import { newPaper, newQuestion, id, DIFFICULTIES, now } from '../data.js';
import { clone, move, contentOf } from '../model.js';
import * as store from '../store.js';
import { editorHeader, sectionNav, validationPanel, wireAuthoring } from '../authoring.js';
import { questionFields, bindQuestion, QUESTION_TYPES } from '../questions.js';
import { problemCodeFields, casesFields, bindCodeAndCases } from './practice.js';
export function renderAssessments(ctx) {
    const parts = ctx.path.split('/').filter(Boolean);
    if (parts[1] === 'companies')
        return companies(ctx, parts[2], parts[3]);
    if (parts[1] === 'tests')
        return recordedTest(ctx, parts[2], parts[3]);
    if (!parts[2])
        return papers(ctx);
    const p = ctx.db.papers.find(x => x.id === parts[2]);
    if (!p)
        return ctx.notFound('Paper not found.');
    if (parts[3] === 'analytics')
        return paperAnalytics(ctx, p);
    if (parts[3] === 'accommodations')
        return accommodations(ctx, p);
    return paperEditor(ctx, p, parts[3]);
}
function papers(ctx) {
    const v = ctx.view;
    const type = ctx.query.get('type') || v.type || 'All';
    const rows = ctx.db.papers.filter(p => (type === 'All' || p.type === type) && (!v.search || p.title.toLowerCase().includes(v.search.toLowerCase())));
    ctx.on('new-paper', () => ctx.dialog('Create a paper', `${field('Title', 'title', '', { required: true })}${field('Type', 'type', type === 'Company' ? 'Company' : 'Mock', { options: ['Mock', 'Company'] })}${field('Company (Company papers only)', 'companyId', '', { options: [['', 'Select a company'], ...ctx.db.companies.filter(c => c.active).map(c => [c.id, c.title])] })}`, { confirm: 'Create draft', onConfirm: values => { if (values.title.trim().length < 2)
            throw Error('Add a clear title.'); if (values.type === 'Company' && !values.companyId)
            throw Error('Select the owning company.'); const p = newPaper(values.type, values.companyId); p.title = values.title.trim(); if (p.type === 'Company')
            p.role = ctx.db.companies.find(c => c.id === p.companyId)?.roles[0] || ''; store.createRecord('papers', p); ctx.navigate(`/admin/papers/${p.id}`, true); } }));
    ctx.on('paper-type', value => ctx.navigate(`/admin/papers${value === 'All' ? '' : `?type=${value}`}`, true));
    ctx.onChange('search', value => { v.search = value; ctx.renderWithFocus('search'); });
    return `${heading('Assessment papers', 'A shared authoring experience. Mock and Company keep their own rules.', button('New paper', 'new-paper', { primary: true, icon: 'plus' }), 'ASSESSMENTS / ADMIN')}${tabs(['All', 'Mock', 'Company'], type, 'paper-type')}<div class="filterbar"><div class="search-box">${icon('search')}<input aria-label="Search papers" data-change="search" placeholder="Search papers…" value="${esc(v.search || '')}"/></div>${link('Manage companies & roles', '/admin/companies', 'btn')}</div>${table(['Paper', 'Type', 'Sections / questions', 'Status', ''], rows.map(p => [`<div class="row-icon"><span class="tile-icon">${icon('shield')}</span><div>${link(p.title, `/admin/papers/${p.id}`, 'row-title')}<small>${p.duration} minutes · ${esc(p.proctoring)} proctoring</small></div></div>`, badge(p.type), `${p.sections.length} / ${p.sections.reduce((n, s) => n + s.questions.length, 0)}`, badge(p.status), link('Open paper →', `/admin/papers/${p.id}`)]))}<p class="page-footnote">${icon('shield')}All papers and results here are fictional local data. No learner attempts are changed.</p>`;
}
function paperEditor(ctx, p, view) {
    const s = ctx.edit('papers', p.id);
    const views = { questions: 'questions', import: 'import', checklist: 'checks', published: 'preview', settings: 'settings' };
    if (view && s.routeView !== view) {
        s.section = views[view] || 'details';
        s.routeView = view;
    }
    const current = s.section || 'details', d = s.draft;
    wireAuthoring(ctx, s, { back: '/admin/papers', preview: () => paperPreview(d) });
    ctx.on('section-select', key => { s.selectedSection = key; s.selectedQuestion = null; ctx.render(); });
    ctx.on('section-add', () => { d.sections.push({ id: id('section'), title: `Section ${d.sections.length + 1}`, subject: 'Aptitude', briefing: '', duration: 0, runAllowance: '', included: true, questions: [] }); s.selectedSection = d.sections.at(-1).id; ctx.markDirty(s); ctx.render(); });
    ctx.on('section-remove', key => ctx.dialog('Remove section', `<p>This removes the section and its questions from the draft. Captured learner tests are not rewritten.</p>`, { confirm: 'Remove section', danger: true, onConfirm: () => { d.sections = d.sections.filter(x => x.id !== key); s.selectedSection = d.sections[0]?.id; ctx.markDirty(s); ctx.render(); } }));
    ctx.on('section-up', key => { d.sections = move(d.sections, d.sections.findIndex(x => x.id === key), -1); ctx.markDirty(s); ctx.render(); });
    ctx.on('section-down', key => { d.sections = move(d.sections, d.sections.findIndex(x => x.id === key), 1); ctx.markDirty(s); ctx.render(); });
    ctx.on('question-select', key => { s.selectedQuestion = key; s.questionTab = 'details'; ctx.render(); });
    const si = Math.max(0, d.sections.findIndex(x => x.id === s.selectedSection)), sec = d.sections[si];
    ctx.on('question-add', () => { if (!sec)
        throw Error('Create a section first.'); ctx.dialog('Add question', field('Question type', 'type', 'single', { options: QUESTION_TYPES }), { confirm: 'Add question', onConfirm: values => { const q = newQuestion(values.type); sec.questions.push(q); s.selectedQuestion = q.id; s.questionTab = 'details'; ctx.markDirty(s); ctx.render(); } }); });
    ctx.on('question-remove', key => ctx.dialog('Remove question', `<p>The question is removed from this draft, not from captured test history.</p>`, { confirm: 'Remove question', danger: true, onConfirm: () => { sec.questions = sec.questions.filter(q => q.id !== key); s.selectedQuestion = null; ctx.markDirty(s); ctx.render(); } }));
    ctx.on('question-up', key => { sec.questions = move(sec.questions, sec.questions.findIndex(x => x.id === key), -1); ctx.markDirty(s); ctx.render(); });
    ctx.on('question-tab', tab => { s.questionTab = tab; ctx.render(); });
    let body = '';
    if (current === 'details')
        body = section('details', 'Paper details', 'The paper type and owning company stay fixed after creation.', `<div class="form-grid">${field('Title', 'title', d.title, { required: true, wide: true })}${field('Type', 'type', d.type, { readonly: true })}${d.type === 'Mock' ? field('Category', 'category', d.category) : field('Owning company', 'companyId', d.companyId, { options: ctx.db.companies.map(c => [c.id, c.title]), disabled: true })}${d.type === 'Mock' ? field('Difficulty', 'difficulty', d.difficulty, { options: DIFFICULTIES }) : field('Job role', 'role', d.role, { options: ctx.db.companies.find(c => c.id === d.companyId)?.roles || [] })}${field(d.type === 'Company' ? 'Briefing instructions' : 'Description & instructions', 'description', d.description, { textarea: true, rows: 7, wide: true })}${d.type === 'Company' ? field('Paper year', 'year', d.year, { type: 'number', min: 2000, max: 2100 }) + field('Source label', 'provenance', d.provenance, { options: ['Pattern', 'Actual'] }) + field('Source reference', 'source', d.source) + field('Source date', 'sourceDate', d.sourceDate, { type: 'date' }) + field('Reproduction permission', 'permission', d.permission, { textarea: true, wide: true, help: 'Required for Actual. Pattern must not imply employer endorsement.' }) : ''}</div>`);
    if (current === 'questions') {
        const qi = sec ? Math.max(0, sec.questions.findIndex(x => x.id === s.selectedQuestion)) : 0, q = sec?.questions[qi];
        if (q) {
            bindQuestion(ctx, q, s);
            if (q.type === 'coding')
                bindCodeAndCases(ctx, q.code, s);
        }
        const prefix = `sections.${si}.questions.${qi}`;
        const qbody = q ? (q.type === 'coding' ? `${tabs([['details', 'Question & marks'], ['code', 'Starter & reference'], ['cases', 'Test cases']], s.questionTab || 'details', 'question-tab')}${s.questionTab === 'code' ? problemCodeFields(q.code, s).replaceAll('data-code="', 'data-code="' + prefix + '.code.').replaceAll('data-field="', 'data-field="' + prefix + '.code.') : s.questionTab === 'cases' ? casesFields(q.code, s).replaceAll('data-field="', 'data-field="' + prefix + '.code.') : questionFields(q, prefix) + `<div class="form-grid mt">${field('Input description', prefix + '.code.inputDescription', q.code.inputDescription, { textarea: true })}${field('Output description', prefix + '.code.outputDescription', q.code.outputDescription, { textarea: true })}${field('Constraints', prefix + '.code.constraints', q.code.constraints, { textarea: true, wide: true })}${field('Execution time (ms)', prefix + '.code.timeMs', q.code.timeMs, { type: 'number', min: 1, max: 10000 })}${field('Memory (MiB)', prefix + '.code.memoryMiB', q.code.memoryMiB, { type: 'number', min: 1, max: 256 })}</div>` + note('The question text is the coding statement. Starters, references and cases remain owned by this paper.')}` : questionFields(q, prefix)) : empty('Add a question', 'Single choice, multiple select, numerical, true/false and coding are supported.', button('Add question', 'question-add', { icon: 'plus' }));
        body = section('questions', 'Sections & questions', 'Arrange the paper and edit questions in the same workspace.', `<div class="language-strip">${d.sections.map(x => `<button class="language-button ${x.id === sec?.id ? 'active' : ''}" data-action="section-select" data-id="${x.id}">${esc(x.title)} ${badge(String(x.questions.length))}</button>`).join('')}${button('Add section', 'section-add', { small: true, icon: 'plus' })}</div>${sec ? `<details class="mb"><summary>Section details & ordering</summary><div class="form-grid mt">${field('Section title', `sections.${si}.title`, sec.title)}${field('Subject', `sections.${si}.subject`, sec.subject)}${field('Briefing', `sections.${si}.briefing`, sec.briefing, { textarea: true, wide: true })}${field('Suggested duration (minutes)', `sections.${si}.duration`, sec.duration, { type: 'number', min: 0, help: 'Pacing guidance, not a separate timer.' })}${field('Visible-case run allowance', `sections.${si}.runAllowance`, sec.runAllowance, { type: 'number', min: 0, help: 'Empty means unlimited.' })}</div>${toggle('Include this section', `sections.${si}.included`, sec.included)}<div class="actions mt">${button('Move up', 'section-up', { id: sec.id, small: true })}${button('Move down', 'section-down', { id: sec.id, small: true })}${button('Remove section', 'section-remove', { id: sec.id, small: true, danger: true })}</div></details>` : ''}<div class="split-workspace"><div class="split-side"><div class="subheading"><h3>Questions</h3>${button('Add', 'question-add', { small: true, icon: 'plus' })}</div>${(sec?.questions || []).map((x, i) => `<button class="case-row ${x.id === q?.id ? 'active' : ''}" data-action="question-select" data-id="${x.id}"><span><strong>${i + 1}. ${esc(x.title || 'Untitled question')}</strong><small>${esc(QUESTION_TYPES.find(t => t[0] === x.type)?.[1])} · ${x.marks} marks</small></span></button>`).join('')}</div><div class="v-splitter" data-split="--left-width" role="separator" aria-label="Resize question list" aria-orientation="vertical" aria-valuenow="260" tabindex="0"></div><div class="split-content">${q ? `<div class="subheading">${badge(QUESTION_TYPES.find(t => t[0] === q.type)?.[1] || q.type)}<div class="actions">${button('Move up', 'question-up', { id: q.id, small: true })}${button('Remove', 'question-remove', { id: q.id, small: true, danger: true })}</div></div>` : ''}${qbody}</div></div>`);
    }
    if (current === 'settings')
        body = section('settings', 'Timing, marking & proctoring', 'Captured tests retain the conditions they started with.', `<div class="form-grid">${field('Duration (minutes)', 'duration', d.duration, { type: 'number', min: 5, max: 240 })}${field('Submission grace (seconds)', 'grace', d.grace, { type: 'number', min: 0, max: 300, help: 'Not extra answering time.' })}${d.type === 'Mock' ? field('Passing percentage', 'passPercent', d.passPercent, { type: 'number', min: 1, max: 100 }) : note('Company papers do not have a pass/fail threshold.')}${field('Proctoring', 'proctoring', d.proctoring, { options: ['Off', 'Standard', 'Strict'] })}${field('Strict counted-event limit', 'eventLimit', d.eventLimit, { type: 'number', min: 1, max: 10 })}${field('Opens', 'opens', d.opens, { type: 'datetime-local' })}${field('Closes', 'closes', d.closes, { type: 'datetime-local' })}</div><div class="grid-two mt"><div>${toggle('Request fullscreen', 'fullscreen', d.fullscreen)}${toggle('Count clipboard/context-menu observations', 'clipboard', d.clipboard)}${toggle('Count restricted navigation', 'restrictedNavigation', d.restrictedNavigation)}${toggle('Feature this paper', 'featured', d.featured)}</div><div>${d.type === 'Mock' ? [['timer', 'Show timer'], ['palette', 'Question palette'], ['review', 'Mark for review'], ['skip', 'Allow skip'], ['revisit', 'Allow revisit'], ['sectionSwitch', 'Allow section switching'], ['shuffleQuestions', 'Shuffle questions'], ['shuffleOptions', 'Shuffle options']].map(([k, l]) => toggle(l, k, d[k])).join('') : note('Company tests use their captured section-locking navigation policy.')}</div></div>${section('reveal', 'Result visibility', 'These settings reveal original answers; they do not change marks.', `${toggle('Reveal original answer key', 'revealAnswers', d.revealAnswers)}${toggle('Reveal original explanations', 'revealExplanations', d.revealExplanations)}`)}${toggle('Notify learners about this update', 'notify', d.notify, 'Optional for Assessment updates.')}${toggle('Grant a fresh recorded test', 'freshTest', d.freshTest, 'Requires the notice. Grants do not stack.')}`);
    if (current === 'preview')
        body = section('preview', 'Paper preview', 'Read-only. No learner attempt is created.', paperPreview(d));
    if (current === 'checks')
        body = section('checks', 'Publication checks', 'Required fields and simulated execution checks are shown together.', note('Use Validate demo in the side panel. A missing coding reference or stale result blocks publication.') + table(['Section', 'Questions', 'Marks'], d.sections.map(x => [esc(x.title), String(x.questions.length), String(x.questions.reduce((sum, q) => sum + Number(q.marks), 0))])));
    if (current === 'import') {
        ctx.on('download-question-template', () => download('questions-template.json', JSON.stringify({ questions: [{ section: 'Reasoning', ...newQuestion('single'), title: 'Example question', options: ['A', 'B'], correct: [0] }] }, null, 2)));
        ctx.on('import-questions', () => { const text = document.querySelector('[data-import-text]')?.value || ''; let data; try {
            data = JSON.parse(text);
        }
        catch {
            throw Error('Invalid JSON. No questions were imported.');
        } if (!Array.isArray(data.questions) || !data.questions.length || data.questions.length > 100)
            throw Error('Provide 1–100 questions.'); const staged = []; for (const [i, row] of data.questions.entries()) {
            const target = d.sections.find(x => x.title === row.section);
            if (!target)
                throw Error(`Row ${i + 1}: unknown section ${row.section}.`);
            if (!QUESTION_TYPES.some(t => t[0] === row.type) || !row.title?.trim())
                throw Error(`Row ${i + 1}: valid type and title required.`);
            staged.push({ target, q: { ...newQuestion(row.type), ...row, id: id('q') } });
        } for (const x of staged)
            x.target.questions.push(x.q); ctx.markDirty(s); ctx.toast(`${staged.length} draft questions imported. Nothing published.`); s.section = 'questions'; ctx.render(); });
        body = section('import', 'Import questions', 'A bounded JSON prototype format. Map each question to an existing section name.', `${note('All rows are checked before this draft changes. No partial imports.')}${button('Download template', 'download-question-template', { icon: 'download' })}<div class="field mt"><label for="question-import">Paste JSON</label><textarea id="question-import" class="mono" rows="15" data-import-text placeholder='{"questions": […]}'></textarea></div><div class="mt">${button('Validate & import into draft', 'import-questions', { primary: true, icon: 'upload' })}</div>`);
    }
    return `${editorHeader(s, '/admin/papers', `ASSESSMENTS / ${d.type.toUpperCase()}`)}${sectionNav([['details', 'Details'], ['questions', 'Sections & questions'], ['settings', 'Settings'], ['preview', 'Preview'], ['import', 'Import'], ['checks', 'Checks']], current)}<div class="subnav-links">${link('Accommodations', `/admin/papers/${d.id}/accommodations`)}${link('Paper analytics', `/admin/papers/${d.id}/analytics`)}</div><div class="editor-layout"><div>${body}</div>${validationPanel(s)}</div>`;
}
function paperPreview(d) { return `<article class="preview-article">${badge(d.type)} ${badge(d.provenance || 'Practice')}<h2>${esc(d.title)}</h2>${markdown(d.description)}<div class="stat-line"><span>${d.duration} minutes · ${esc(d.proctoring)} proctoring</span><b>${d.sections.reduce((sum, x) => sum + x.questions.length, 0)} questions</b></div>${d.sections.filter(s => s.included).map(s => `<h3 class="mt">${esc(s.title)}</h3><p>${esc(s.briefing)}</p>${s.questions.map((q, i) => `<p><b>${i + 1}.</b> ${esc(q.title)} <small>(${q.marks} marks)</small></p>`).join('')}`).join('')}</article>`; }
function companies(ctx, companyId, view) {
    if (companyId && view === 'analytics') {
        const c = ctx.db.companies.find(x => x.id === companyId);
        return c ? paperAnalytics(ctx, { id: companyId, title: c.title, type: 'Company', sections: [] }) : ctx.notFound('Company not found.');
    }
    const selected = ctx.query.get('company');
    const company = ctx.db.companies.find(x => x.id === selected);
    ctx.on('new-company', () => ctx.dialog('New company', `${field('Company name', 'title', '', { required: true })}${field('Description', 'description', '', { textarea: true })}`, { confirm: 'Create company', onConfirm: v => { store.requireSuper(); if (!v.title.trim())
            throw Error('Name required.'); const c = { id: id('company'), ...v, roles: [], marks: 4, penalty: 0, customDefaults: false, active: true, revision: 1, updated: now() }; store.createRecord('companies', c); ctx.navigate(`/admin/companies?company=${c.id}`, true); } }));
    if (!company)
        return `${heading('Companies & job roles', 'Keep company context clear. Job roles are not Labs permissions.', button('New company', 'new-company', { primary: true, icon: 'plus', disabled: store.role !== 'Super Admin' }), 'ASSESSMENTS / ADMIN')}${table(['Company', 'Roles', 'Papers', 'State', ''], ctx.db.companies.map(c => [link(c.title, `/admin/companies?company=${c.id}`, 'row-title'), String(c.roles.length), String(ctx.db.papers.filter(p => p.companyId === c.id).length), badge(c.active ? 'Active' : 'Inactive'), link('Manage →', `/admin/companies?company=${c.id}`)]))}`;
    const s = ctx.edit('companies', company.id), d = s.draft;
    ctx.editing = s;
    ctx.fields(d, () => ctx.markDirty(s));
    ctx.on('company-save', () => { store.requireSuper(); if (new Set(d.roles.map(x => x.toLowerCase().trim())).size !== d.roles.length || d.roles.some(x => !x.trim()))
        throw Error('Job role names must be nonempty and unique within the company.'); s.draft = store.saveRecord('companies', d, s.baseRevision); s.baseRevision = s.draft.revision; s.dirty = false; ctx.render(); ctx.toast('Company changes saved locally.'); });
    ctx.on('company-role-add', () => { d.roles.push(''); ctx.markDirty(s); ctx.render(); });
    ctx.on('company-role-remove', v => { const i = Number(v); if (ctx.db.papers.some(p => p.companyId === d.id && p.role === d.roles[i]))
        throw Error('A paper still uses this role. Correct its reference before removal.'); d.roles.splice(i, 1); ctx.markDirty(s); ctx.render(); });
    ctx.on('company-toggle', () => ctx.dialog(d.active ? 'Deactivate company' : 'Restore company', `<p>Existing paper history is preserved. This changes future catalogue availability.</p>`, { confirm: d.active ? 'Deactivate' : 'Restore', onConfirm: () => { store.update(db => db.companies.find(x => x.id === d.id).active = !d.active, 'Changed company availability', d.title, true); ctx.dropSession(s); ctx.render(); } }));
    return `${heading(d.title, 'Edit the company and its job roles in one place.', `${link('Back', '/admin/companies', 'btn')}${button(d.active ? 'Deactivate' : 'Restore', 'company-toggle', { disabled: store.role !== 'Super Admin' })}${button('Save company', 'company-save', { primary: true, icon: 'save', disabled: store.role !== 'Super Admin' })}`, 'ASSESSMENTS / COMPANY')}${section('company', 'Company details', 'Changes do not rewrite captured test identity.', `<div class="form-grid">${field('Name', 'title', d.title, { required: true })}${field('Description', 'description', d.description, { textarea: true, wide: true })}${field('Default marks for new questions', 'marks', d.marks, { type: 'number', min: 1 })}${field('Default negative marks', 'penalty', d.penalty, { type: 'number', min: 0 })}</div>`)}${section('roles', 'Job roles', 'Unique within this company.', `${d.roles.map((r, i) => `<div class="option-row">${field(`Role ${i + 1}`, `roles.${i}`, r)}${button('Remove', 'company-role-remove', { id: String(i), small: true })}</div>`).join('')}${button('Add job role', 'company-role-add', { icon: 'plus' })}`)}`;
}
function accommodations(ctx, p) { ctx.on('accommodation-save', () => { const person = document.querySelector('[data-accommodation-person]').value, multiplier = document.querySelector('[data-accommodation-multiplier]').value; if (!person)
    throw Error('Select a learner.'); ctx.dialog('Confirm pre-start accommodation', `<p>${esc(person)} receives ${multiplier}× answering time on ${esc(p.title)}. Submission grace is unchanged.</p>`, { typed: person, reason: true, confirm: 'Save accommodation', onConfirm: v => { store.update(d => { d.accommodations ||= []; const existing = d.accommodations.find(x => x.paperId === p.id && x.person === person); if (existing)
        existing.multiplier = multiplier;
    else
        d.accommodations.push({ paperId: p.id, person, multiplier }); return v.reason; }, 'Granted pre-start accommodation', person, true); ctx.toast('Demo accommodation recorded.'); ctx.render(); } }); }); return `${heading('Accommodations', p.title, link('Back to paper', `/admin/papers/${p.id}`, 'btn'), 'ASSESSMENTS / PRE-START')} ${section('accommodations', 'Additional answering time', 'No medical evidence is requested or retained.', `<div class="form-grid"><div class="field"><label>Learner</label><select aria-label="Learner" data-accommodation-person>${ctx.db.people.filter(p => p.role === 'User').map(x => `<option>${esc(x.title)}</option>`).join('')}</select></div><div class="field"><label>Multiplier</label><select aria-label="Multiplier" data-accommodation-multiplier>${['1.0', '1.25', '1.5', '2.0'].map(v => `<option>${v}</option>`).join('')}</select></div></div><div class="mt">${button('Review accommodation', 'accommodation-save', { primary: true, disabled: store.role !== 'Super Admin' })}</div>`)}${table(['Learner', 'Multiplier'], (ctx.db.accommodations || []).filter(x => x.paperId === p.id).map(x => [esc(x.person), esc(x.multiplier) + '×']))}`; }
function recordedTest(ctx, testId, view) { const t = ctx.db.testRecords.find(x => x.id === testId); if (!t)
    return ctx.notFound('No demo test has that identifier. The sample test is test-demo.'); ctx.on('invalidate', () => ctx.dialog('Invalidate this test', `<p>Keep the history entry, restore the allowed test opportunity and record the neutral learner-facing consequence. You cannot select a replacement score.</p>`, { typed: t.title, reason: true, confirm: 'Invalidate demo test', danger: true, onConfirm: v => { if (t.status === 'Invalidated')
        throw Error('Already invalidated; no duplicate effect.'); store.update(d => { const row = d.testRecords.find(x => x.id === t.id); row.status = 'Invalidated'; row.history.push(v.reason); }, 'Invalidated recorded test', t.title, true); ctx.render(); } })); return `${heading(view === 'invalidate' ? 'Result invalidation' : 'Recorded events', t.title, `${badge(t.status)}${button('Invalidate test', 'invalidate', { danger: true, disabled: store.role !== 'Super Admin' || t.status === 'Invalidated' })}`, 'ASSESSMENTS / TEST RECORD')}${note('Fictional browser observations, not recordings and not an accusation.')}${table(['Time', 'Observation', 'Counted'], t.events.map(e => [esc(e.time), esc(e.event), badge(e.counted ? 'Yes' : 'No')]))}${section('ending', 'How the test ended', 'Read-only recorded facts.', `<p>${esc(t.ending)} · ${esc(t.proctoring)} proctoring</p>`)}${link('Return to papers', '/admin/papers', 'btn')}`; }
export function paperAnalytics(ctx, p) { ctx.on('export-paper-report', () => download('paper-report.csv', csv([['Paper', 'Type', 'Starts', 'Finalized'], [p.title, p.type, 80, 64]]), 'text/csv')); return `${heading(`${p.title} · analytics`, 'Illustrative aggregates only. Company results never acquire a pass/fail score.', button('Export sample', 'export-paper-report', { icon: 'download' }), 'ASSESSMENTS / REPORTING')}${note('Seeded demonstration figures; no live analytics or learner rows.')}<div class="metrics">${metric('Started', 80, 'Sample recorded tests')}${metric('Finalized', 64, 'Excludes practice mode')}${metric('Completion rate', '80%', '64 finalized / 80 starts')}${metric(p.type === 'Mock' ? 'Pass rate' : 'Average score', p.type === 'Mock' ? '72%' : '68%', 'Sample finalized population')}</div>${section('questions', 'Question review', 'Neutral signals invite inspection.', table(['Question', 'Accuracy', 'Review signal'], [['Reasoning example', '78%', 'No current flag'], ['Coding example', '42%', 'Inspect examples and constraints']]))}${link('Back to papers', '/admin/papers', 'btn')}`; }
