import { esc, icon, button, link, badge, field, toggle, section, heading, table, empty, note, markdown } from '../ui.js';
import { id, now, dateAfter, MESSAGE_KINDS, EXPRESSIONS, TONES } from '../data.js';
import { clone } from '../model.js';
import { editorHeader, validationPanel, wireAuthoring } from '../authoring.js';
import * as store from '../store.js';
export function renderWizbit(ctx) { const page = ctx.path.split('/').at(-1); if (page === 'kb')
    return knowledge(ctx); if (page === 'responses')
    return responses(ctx); if (page === 'kb-administration')
    return matching(ctx); if (page === 'identity')
    return identity(ctx); if (page === 'nudges')
    return nudges(ctx); return ctx.notFound(); }
function knowledge(ctx) {
    const key = ctx.query.get('entry');
    if (!key) {
        ctx.on('kb-new', () => ctx.dialog('Create product-help entry', field('Question it answers', 'title', '', { required: true }), { confirm: 'Create draft', onConfirm: v => { if (v.title.trim().length < 2)
                throw Error('Enter a question.'); const r = { id: id('kb'), title: v.title, answer: '', synonyms: '', tags: '', source: '', reviewed: dateAfter(0), revision: 1, status: 'Draft', updated: now() }; store.createRecord('kb', r); ctx.navigate(`/admin/wizbit/kb?entry=${r.id}`, true); } }));
        return `${heading('Product-help knowledge', 'Authored answers about Labs. No model-generated guesses or learner transcripts.', button('Create entry', 'kb-new', { primary: true, icon: 'plus' }), 'PLATFORM / WIZBIT')}${table(['Question', 'Status', 'Reviewed', ''], [...ctx.db.kb].sort((a, b) => (a.reviewed || '').localeCompare(b.reviewed || '')).map(r => [link(r.title, `/admin/wizbit/kb?entry=${r.id}`, 'row-title'), badge(r.status), esc(r.reviewed || 'Never reviewed'), link('Edit entry', `/admin/wizbit/kb?entry=${r.id}`, 'btn small')]))}${note('Published overdue answers continue working. Unpublish stops an entry from answering without deleting its history.')}`;
    }
    const s = ctx.edit('kb', key);
    if (!s)
        return ctx.notFound();
    wireAuthoring(ctx, s, { back: '/admin/wizbit/kb', preview: () => `<article class="preview-article"><h2>${esc(s.draft.title)}</h2>${markdown(s.draft.answer)}<p class="muted">Authored product guidance · no learner data</p></article>` });
    const d = s.draft;
    return `${editorHeader(s, '/admin/wizbit/kb', 'WizBit / knowledge base')}<div class="editor-layout"><div>${section('content', 'One useful answer', 'Write the answer a learner actually needs, with a reference to the product rule.', `<div class="form-grid">${field('Question', 'title', d.title, { wide: true, required: true })}${field('Authored answer', 'answer', d.answer, { textarea: true, rows: 10, wide: true })}${field('Synonyms', 'synonyms', d.synonyms, { help: 'Alternative question wording, separated by commas.' })}${field('Tags', 'tags', d.tags)}${field('Product-rule reference', 'source', d.source, { wide: true, required: true })}${field('Last reviewed', 'reviewed', d.reviewed, { type: 'date' })}</div>`)}</div>${validationPanel(s)}</div>`;
}
function responses(ctx) {
    const s = ctx.edit('responseSets', 'responses-main');
    if (!s)
        return ctx.notFound('Reset the prototype to initialize the coordinated response set.');
    s.selected ??= 0;
    const d = s.draft, i = Math.min(s.selected, d.items.length - 1), r = d.items[i];
    const prefix = `items.${i}`;
    wireAuthoring(ctx, s, { back: '/admin/wizbit/kb', preview: () => `<div class="grid-two"><article class="preview-article"><h3>Companion presentation</h3><span class="orb" aria-hidden="true">${icon('spark')}</span>${badge(r.expression)}<p>${esc(r.fact)}</p><small>${esc(r.flourish)}</small></article><article class="preview-article"><h3>Plain presentation</h3><p>${esc(r.fact)}</p></article></div>${note('Preview only. No learner message is sent, and the companion is not active in administration.')}` });
    ctx.on('response-select', key => { s.selected = Number(key); ctx.render(); });
    const controls = `<div class="form-grid">${field('Required factual sentence', `${prefix}.fact`, r.fact, { textarea: true, rows: 4, wide: true, maxlength: 500, help: 'Must stand alone. Up to 500 characters; no hidden material or invented outcome.' })}${field('Optional flourish', `${prefix}.flourish`, r.flourish, { textarea: true, rows: 2, wide: true, maxlength: 240 })}${field('Tone', `${prefix}.tone`, r.tone, { options: TONES })}${field('Expression', `${prefix}.expression`, r.expression, { options: EXPRESSIONS })}${toggle('Requires acknowledgement', `${prefix}.acknowledgement`, r.acknowledgement)}${toggle('Celebration eligible', `${prefix}.celebrate`, r.celebrate, 'Presence and kind-specific restrictions still apply.')}</div><div class="grid-two"><div class="preview-article"><h4>Companion copy</h4><p data-response-fact>${esc(r.fact)}</p><small data-response-flourish>${esc(r.flourish)}</small></div><div class="preview-article"><h4>Plain copy</h4><p data-response-plain>${esc(r.fact)}</p></div></div>`;
    const old = ctx.fieldChanged;
    ctx.fieldChanged = (path) => { old?.(path); document.querySelectorAll('[data-response-fact],[data-response-plain]').forEach(e => e.textContent = r.fact); const f = document.querySelector('[data-response-flourish]'); if (f)
        f.textContent = r.flourish; };
    return `${editorHeader(s, '/admin/wizbit/kb', 'WizBit / all 39 message kinds')}${note('This seeded wording is demonstration content. Publish checks the entire coordinated set, not just the selected message. No live messages are delivered.')}<div class="split-workspace"><aside class="split-side response-list"><div class="tree-heading">${icon('spark')} Message catalogue <b>39</b></div>${d.items.map((x, j) => `<button class="tree-item ${j === i ? 'selected' : ''}" data-action="response-select" data-id="${j}"><span class="muted">${String(j + 1).padStart(2, '0')}</span><span>${esc(x.title)}</span>${x.fact.trim() ? icon('check') : icon('alert')}</button>`).join('')}</aside><div class="v-splitter" role="separator" aria-label="Resize message catalogue" aria-orientation="vertical" tabindex="0" data-split="--left-width" aria-valuenow="260"></div><div class="editor-layout response-editor"><div>${section('content', r.title, 'Change the wording, not the producer’s meaning or authority.', controls)}</div>${validationPanel(s)}</div></div>`;
}
function matching(ctx) {
    const v = ctx.view;
    v.settings ||= { matchThreshold: ctx.db.settings.matchThreshold, matchMargin: ctx.db.settings.matchMargin };
    ctx.fields(v.settings);
    const tests = [['Do hints cost anything?', 0.92, 0.28, 'Answer'], ['Where do I practise?', 0.71, 0.08, 'Clarify'], ['Repair my private program', 0.31, 0.02, 'No match']];
    ctx.on('matching-preview', () => { const t = Number(v.settings.matchThreshold), m = Number(v.settings.matchMargin); if (!Number.isFinite(t) || !Number.isFinite(m) || t < 0 || t > 1 || m < 0 || m > 1)
        throw Error('Both demo matching controls must be between 0 and 1.'); ctx.dialog('Evaluate proposed matching policy', note('These are authored test questions and fixed illustrative scores. No real search engine or learner transcript is used.') + table(['Test question', 'Score', 'Margin', 'Proposed outcome'], tests.map(([q, s, g]) => [q, String(s), String(g), s >= t && g >= m ? 'Answer' : 'Clarify / no clear match'])), { confirm: 'Apply policy', onConfirm: () => { store.update(d => { d.settings.matchThreshold = t; d.settings.matchMargin = m; }, 'Changed matching policy', 'WizBit', true); ctx.toast('Demo matching policy saved.'); ctx.render(); } }); });
    return `${heading('Knowledge matching controls', 'Preview changes against authored questions, not private learner conversations.', button('Preview evaluation', 'matching-preview', { primary: true, icon: 'play', disabled: store.role !== 'Super Admin' }), 'PLATFORM / WIZBIT')}${section('settings', 'Matching policy', 'These settings gate authored answers. They are not learner-facing confidence claims.', `<div class="form-grid">${field('Minimum match score', 'matchThreshold', v.settings.matchThreshold, { type: 'number', step: 0.01, min: 0, max: 1 })}${field('Margin over runner-up', 'matchMargin', v.settings.matchMargin, { type: 'number', step: 0.01, min: 0, max: 1 })}</div>`)}${section('evaluation', 'Private authored evaluation set', 'Three representative questions for the demonstration.', table(['Question', 'Expected interpretation'], tests.map(([q, s, g, out]) => [esc(q), out])))}${note('No arbitrary per-entry relevance boost. Production matching thresholds and the full evaluation corpus retain the approved shared policy.')}`;
}
function identity(ctx) {
    const v = ctx.view;
    v.draft ||= { character: ctx.db.settings.character, characterAccent: ctx.db.settings.characterAccent };
    ctx.fields(v.draft);
    ctx.on('identity-save', () => { if (!/^#[0-9a-f]{6}$/i.test(v.draft.characterAccent))
        throw Error('Choose a valid hexadecimal accent.'); store.update(d => Object.assign(d.settings, v.draft), 'Changed character presentation', 'WizBit', true); ctx.toast('Demo presentation saved. No default-name change or skin store.'); });
    return `${heading('Character presentation', 'Inspect a complete expression set, including static reduced-motion treatment.', button('Apply presentation', 'identity-save', { primary: true, disabled: store.role !== 'Super Admin' }), 'PLATFORM / WIZBIT')}${note('The abstract artwork below is prototype-only. Final approved character assets are not claimed to be complete.')}${section('identity', 'Presentation', 'WizBit is the fixed product name. A learner’s chosen name remains their own.', `<div class="form-grid">${field('Demo artwork', 'character', v.draft.character, { options: ['Orbital', 'Outline'] })}${field('Character accent', 'characterAccent', v.draft.characterAccent, { type: 'color' })}</div><div class="expression-grid">${EXPRESSIONS.map((e, i) => `<div class="expression-card"><div class="orb ${v.draft.character === 'Outline' ? 'outline' : ''}" style="--orb-accent:${esc(v.draft.characterAccent)}" aria-hidden="true">${icon(i === 5 || i === 6 ? 'alert' : i === 7 ? 'check' : i === 8 ? 'spark' : 'eye')}</div><b>${e}</b><small>Static fallback provided</small></div>`).join('')}</div>`)}`;
}
function nudges(ctx) { const v = ctx.view; v.draft ||= { nudgeEnabled: ctx.db.settings.nudgeEnabled, nudgeAllowance: ctx.db.settings.nudgeAllowance ?? 1, nudgeDays: ctx.db.settings.nudgeDays }; ctx.fields(v.draft); ctx.on('nudges-save', () => { const x = v.draft; if (![0, 1].includes(Number(x.nudgeAllowance)) || !Number.isInteger(Number(x.nudgeDays)) || x.nudgeDays < 7 || x.nudgeDays > 30)
    throw Error('Keep allowance at zero or one and cooldown between 7–30 days.'); store.update(d => Object.assign(d.settings, { nudgeEnabled: x.nudgeEnabled, nudgeAllowance: Number(x.nudgeAllowance), nudgeDays: Number(x.nudgeDays) }), 'Changed nudge policy', 'WizBit', true); ctx.toast('Nudge policy saved. No withheld suggestion is replayed.'); }); return `${heading('Proactive guidance', 'Reduce interruptions. Never add promotional producers or relax safety ceilings.', button('Apply policy', 'nudges-save', { primary: true, disabled: store.role !== 'Super Admin' }), 'PLATFORM / WIZBIT')}${section('producer', 'Skills next-action producer', 'Only the existing Home suggestion is eligible.', `${toggle('Enable the approved producer', 'nudgeEnabled', v.draft.nudgeEnabled)}<div class="form-grid">${field('Maximum per product day', 'nudgeAllowance', v.draft.nudgeAllowance, { options: [['0', '0 · disabled'], ['1', '1 · at most one']] })}${field('Same-target cooldown (days)', 'nudgeDays', v.draft.nudgeDays, { type: 'number', min: 7, max: 30 })}</div><div class="stat-line"><span>Minimum gap</span><b>60 minutes · fixed</b></div><div class="stat-line"><span>Platform ceiling</span><b>2/day · not permission for a second producer</b></div>${note('Quiet, active tests, unsafe work and a dismissed unchanged suggestion still prevent delivery. This simulation sends no nudge.')}`)}`; }
