/**
 * editor-theme — keeps an editor painted from the live palette tokens.
 *
 * The theme itself is generated by `defineTokenMonacoTheme` (the extraction
 * library's). This hook takes Monaco from the editor's own `beforeMount`
 * rather than `useMonaco()`, whose loader promise is cancelled without a
 * handler when React re-runs effects, and repaints whenever an appearance
 * attribute on the document changes.
 *
 * A theme change resets every model's syntax tokens, and Monaco rebuilds them
 * in idle time — which a page with live animation may never grant, leaving code
 * uncoloured. After a repaint the open models are re-tokenized straight away.
 */

import { useCallback, useEffect, useRef } from "react";
import type { BeforeMount } from "@monaco-editor/react";
import { defineTokenMonacoTheme } from "../../extraction/components/CodeEditorChrome/monacoTheme";

type MonacoApi = Parameters<typeof defineTokenMonacoTheme>[0];

/* Not in Monaco's public typings; present on every text model at runtime. */
interface TokenizedModel {
  getLineCount(): number;
  tokenization?: { forceTokenization?: (lineNumber: number) => void };
}

const RETOKENIZE_LINE_LIMIT = 2000;

function retokenizeModels(monaco: MonacoApi): void {
  for (const model of monaco.editor.getModels() as unknown as TokenizedModel[]) {
    model.tokenization?.forceTokenization?.(Math.min(model.getLineCount(), RETOKENIZE_LINE_LIMIT));
  }
}

const APPEARANCE_ATTRS = ["data-theme", "data-scheme", "data-subtheme", "data-accent"];

export const EDITOR_THEME = "x-editor-tokens";

export function useLiveEditorTheme(): {
  hostRef: React.RefObject<HTMLDivElement | null>;
  beforeMount: BeforeMount;
  theme: string;
} {
  const hostRef = useRef<HTMLDivElement>(null);
  const monacoRef = useRef<MonacoApi | null>(null);

  const repaint = useCallback(() => {
    const monaco = monacoRef.current;
    if (!monaco) return;
    monaco.editor.setTheme(defineTokenMonacoTheme(monaco, hostRef.current));
    retokenizeModels(monaco);
  }, []);

  useEffect(() => {
    const observer = new MutationObserver(repaint);
    observer.observe(document.documentElement, { attributes: true, attributeFilter: APPEARANCE_ATTRS });
    return () => observer.disconnect();
  }, [repaint]);

  const beforeMount = useCallback<BeforeMount>((monaco) => {
    monacoRef.current = monaco as unknown as MonacoApi;
    defineTokenMonacoTheme(monacoRef.current, hostRef.current);
  }, []);

  return { hostRef, beforeMount, theme: EDITOR_THEME };
}
